# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 20:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True, verbose_name='구매서번호')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='구매일자')),
            ],
            options={
                'verbose_name': '구매요청서',
                'verbose_name_plural': '구매요청서',
            },
        ),
        migrations.CreateModel(
            name='BuyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='수량')),
                ('update', models.DateTimeField(auto_now=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('buy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buy.Buy')),
            ],
            options={
                'verbose_name': '구매품목',
                'verbose_name_plural': '구매품목',
            },
        ),
    ]
