# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 20:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
        ('buy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.BuyProfile'),
        ),
        migrations.AddField(
            model_name='buy',
            name='commiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
