# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 23:20
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buy', '0002_auto_20171107_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_date', models.DateField(default=datetime.date.today, verbose_name='입고일자')),
                ('stock_amount', models.IntegerField(verbose_name='입고수량')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '구매입고',
                'verbose_name_plural': '구매입고',
            },
        ),
        migrations.RenameField(
            model_name='buyitem',
            old_name='amount',
            new_name='buy_amount',
        ),
        migrations.RenameField(
            model_name='buyitem',
            old_name='create',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='buyitem',
            old_name='update',
            new_name='updated',
        ),
        migrations.AddField(
            model_name='buyitem',
            name='completed',
            field=models.BooleanField(default=False, editable=False, verbose_name='입고완료'),
        ),
        migrations.AddField(
            model_name='buyitem',
            name='force_end',
            field=models.BooleanField(default=False, verbose_name='강제종결'),
        ),
        migrations.AddField(
            model_name='buyitem',
            name='incompleted_amount',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='미입고수량'),
        ),
        migrations.AddField(
            model_name='buyitem',
            name='stocked_amount',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='입고수량'),
        ),
        migrations.AddField(
            model_name='buystock',
            name='buyitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buy.BuyItem'),
        ),
        migrations.AddField(
            model_name='buystock',
            name='stock_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
