# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0003_auto_20171108_2320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buy',
            old_name='date',
            new_name='buy_date',
        ),
        migrations.RenameField(
            model_name='buy',
            old_name='slug',
            new_name='buy_num',
        ),
    ]
