# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 22:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_buyprofile_active'),
        ('buy', '0004_auto_20171109_1946'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='buyitem',
            unique_together=set([('buy', 'item')]),
        ),
    ]
