# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 23:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0005_auto_20171109_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyitem',
            name='buy_amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, '1 이상의 값을 입력 해야합니다')], verbose_name='수량'),
        ),
        migrations.AlterUniqueTogether(
            name='buyitem',
            unique_together=set([]),
        ),
    ]
