# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0005_auto_20171107_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='계약가격')),
                ('box_amount', models.IntegerField(blank=True, null=True, verbose_name='박스수량')),
                ('buy_unit', models.CharField(blank=True, choices=[('BOX', 'BOX'), ('BTL', 'BTL')], max_length=10, null=True, verbose_name='구매단위')),
                ('amount_unit', models.CharField(choices=[('포장', '포장'), ('박스', '박스')], default='포장', max_length=10, verbose_name='구매수량법')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Market')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            options={
                'verbose_name': '구매정보',
                'verbose_name_plural': '구매정보',
            },
        ),
        migrations.CreateModel(
            name='StockProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkg_amount', models.IntegerField(verbose_name='포장수량')),
                ('std_unit', models.CharField(choices=[('TAB', 'TAB'), ('AMP', 'AMP')], default='TAB', max_length=10, verbose_name='포장단위')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            options={
                'verbose_name': '재고정보',
                'verbose_name_plural': '재고정보',
            },
        ),
    ]
