# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_product_markets'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyprofile',
            name='market',
        ),
        migrations.AddField(
            model_name='buyprofile',
            name='markets',
            field=models.ManyToManyField(to='product.Market'),
        ),
    ]
