# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20171107_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyprofile',
            name='amount_unit',
        ),
        migrations.AddField(
            model_name='buyprofile',
            name='buybox',
            field=models.BooleanField(default=False, verbose_name='묶음단위구매'),
        ),
        migrations.AlterField(
            model_name='buyprofile',
            name='box_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='묶음수량'),
        ),
        migrations.AlterField(
            model_name='buyprofile',
            name='buy_unit',
            field=models.CharField(blank=True, choices=[('BOX', 'BOX'), ('PKG', 'PKG')], max_length=10, null=True, verbose_name='묶음단위'),
        ),
        migrations.AlterField(
            model_name='stockprofile',
            name='std_unit',
            field=models.CharField(choices=[('AMP', 'AMP'), ('VIAL', 'VIAL'), ('PEN', 'PEN'), ('TAB', 'TAB'), ('BTL', 'BTL')], default='TAB', max_length=10, verbose_name='기본단위'),
        ),
    ]
