# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20171107_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockprofile',
            name='std_unit',
            field=models.CharField(choices=[('AMP', 'AMP'), ('VIAL', 'VIAL'), ('PEN', 'PEN'), ('TAB', 'TAB'), ('BTL', 'BTL'), ('포', '포')], default='TAB', max_length=10, verbose_name='기본단위'),
        ),
    ]
