# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20171107_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyprofile',
            name='price',
        ),
        migrations.AddField(
            model_name='buyprofile',
            name='buy_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='구매가격'),
            preserve_default=False,
        ),
    ]
