# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='도매상명')),
                ('tel', models.CharField(max_length=30, verbose_name='전화')),
                ('fax', models.CharField(max_length=30, verbose_name='팩스')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='제품명')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='제품코드')),
                ('price', models.IntegerField(default=0, verbose_name='가격')),
                ('markets', models.ManyToManyField(blank=True, to='product.Market')),
            ],
        ),
    ]
