# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='market',
            options={'verbose_name': '도매상', 'verbose_name_plural': '도매상'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '제품', 'verbose_name_plural': '제품'},
        ),
        migrations.AddField(
            model_name='market',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='market',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
