# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20171106_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='fax',
            field=models.CharField(blank=True, max_length=30, verbose_name='팩스'),
        ),
        migrations.AlterField(
            model_name='market',
            name='tel',
            field=models.CharField(blank=True, max_length=30, verbose_name='전화'),
        ),
    ]
