# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 20:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20171106_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(2999, 12, 31), null=True, verbose_name='거래종료일'),
        ),
        migrations.AddField(
            model_name='market',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='거래개시일'),
        ),
    ]
