# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 20:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20171107_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='markets',
        ),
    ]
