# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_product_markets'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='markets',
            field=models.ManyToManyField(blank=True, to='product.Market'),
        ),
    ]
