# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_markets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='std_price',
            field=models.IntegerField(default=0, verbose_name='표준가격'),
        ),
    ]
